### ISSUE TITLE
EventDispathcer instance is not a valid

### ISSUE THREAD

**Issue by tlfbrito** [driftphp/skeleton#2]
After creating the skeleton project, I'm getting:
```
400 GET    / (396 μs | 18 MB) - The EventDispathcer instance is not a valid Drift\HttpKernel\AsyncEventDispatcherInterface instance. Symfony\Component\EventDispatcher\EventDispatcher passed.
```

**Comment by mmoreram** [comment]
Thanks so much, @tiagobrito !
Checking this!

**Comment by tlfbrito** [comment]
You are welcome. Congrats for this project!

**Comment by Manuelacosta98** [comment]
This is only happening with the server running in dev mode, without the watcher.

**Comment by mmoreram** [comment]
@tiagobrito can you check that this is not happening anymore? If is OK, feel free to close the Issue :D

Thanks!

**Comment by tlfbrito** [comment]
it isn't! Thanks a lot!
