### ISSUE TITLE
Missing documentation for Command Bus

### ISSUE THREAD

**Issue by developernaren** [driftphp/skeleton#5]
![Screenhost of missing section](https://user-images.githubusercontent.com/3628468/76169861-f5cb8a80-6195-11ea-8ba0-915dd21e40a8.png)
Documentation for this section is missing.

**Comment by mmoreram** [comment]
@developernaren I will check all the docs during this week :)

Thanks!

**Comment by mmoreram** [comment]
@developernaren fixed, thanks :)

Docs disappear after a duplicated content fix.
